apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "app.fullname" . }}-configmap"
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  cli.sh: |
    #!/bin/sh
    echo "CLI START"
